package site.xulian.cake.model;

import java.util.List;

import com.jfinal.ext.plugin.tablebind.TableBind;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

import site.xulian.cake.model.base.BaseComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TableBind(tableName = "comment")
public class Comment extends BaseComment<Comment> {
	public static final Comment dao = new Comment();
	/**
	 * 获取评论信息
	 * @param shopId
	 * @return
	 * */
	public List<Record> getAllcomment(Integer shopId){
		StringBuffer sql = new StringBuffer();
		sql.append("SELECT c.content,c.nikename,c.update_time");
		sql.append(" from `comment` c JOIN `order` o on(c.order_id = o.order_id)");
		sql.append(" WHERE o.shop_id = ?");
		return Db.find(sql.toString(),shopId);
	}
	public String saveComment(String phone,String orderId,String content){
		Users user = Users.dao.findFirst("SELECT * FROM users where phone = ?",phone);		
		if(null != user){
			return Db.update("INSERT INTO comment(user_id,nikename,content,order_id,create_time,update_time,status) values(?,?,?,?,now(),now(),1)",user.getId(),user.getNikename(),content,orderId)>0?"":"提交评论失败！";
		}
		return "";
	}
}
