package site.xulian.cake.model;

import com.jfinal.ext.plugin.tablebind.TableBind;

import site.xulian.cake.model.base.BaseGoodsType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TableBind(tableName = "goods_type")
public class GoodsType extends BaseGoodsType<GoodsType> {
	public static final GoodsType dao = new GoodsType();
}
