package site.xulian.cake.model;

import java.util.List;

import com.jfinal.ext.plugin.tablebind.TableBind;
import com.jfinal.log.Logger;
import com.jfinal.plugin.activerecord.Db;

import site.xulian.cake.model.base.BaseMember;
import site.xulian.cake.utils.MD5Salt;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TableBind(tableName = "member")
public class Member extends BaseMember<Member> {
	public static final Member dao = new Member();
	Logger logger = Logger.getLogger(this.getClass());
	/**
	 * 用户登录
	 * */
	public boolean login(String userName,String password,Integer type){
		logger.info("用户信息：用户名"+userName+",类型："+type);
		password = MD5Salt.md5Salt(password, false);//将密码加密
		List<Member> memberList = Member.dao.find("SELECT * FROM member where username = ? and password = ? and type=? ",userName,password,type);
		if(null != memberList && !memberList.isEmpty()){
			Db.update("UPDATE member set latest_login = now()");//记录登录时间
			return true;
		}
		return false;
	}
}
