package site.xulian.cake.model;

import site.xulian.cake.model.base.BaseNewsType;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NewsType extends BaseNewsType<NewsType> {
	public static final NewsType dao = new NewsType().dao();
	/**
	 * 获取所有新闻类型
	 * */
	public List<NewsType> getNewsTypes(){
		return find("SELECT  * FROM news_type");
	}
}
