package site.xulian.cake.model;

import com.jfinal.ext.plugin.tablebind.TableBind;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

import site.xulian.cake.model.base.BaseShop;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TableBind(tableName = "shop")
public class Shop extends BaseShop<Shop> {
	public static final Shop dao = new Shop();
	/**
	 * 保存店铺信息
	 * */
	public String saveShop(String name,String phone,Integer status,String address){
		return Db.update("INSERT INTO shop(name,phone,address,status,update_time,create_time) VALUES(?,?,?,?,now(),now())",name,phone,address,status)>0?"":"保存失败!";
	}
	/**
	 * 获取店铺信息
	 * */
	public Shop getShop(Integer id){
		return findFirst("SELECT * FROM shop WHERE id = ? limit 1",id);
	}
	/**
	 * 修改店铺信息
	 * */
	public String updateShop(Integer id,String name,String phone,Integer status,String address){
		return Db.update("UPDATE shop SET name =? ,phone = ? ,status =? ,address = ? ,update_time = now() WHERE id = ?",name,phone,status,address,id)>0?"":"修改店铺信息失败！";
	}
	/**
	 * 批量删除店铺信息
	 * */
	public String delShop(Integer id){
		return Db.update("UPDATE shop SET status =? WHERE id = ?",0,id)>0?"":"删除店铺信息失败！";
	}
}
